CRITERIA = [
    {"key": "Originality", "synonyms": ["Novelty", "Originality and Novelty"],
     "desc": "Is the contribution new and clearly differentiated?"},
    {"key": "Soundness", "synonyms": ["Technical Quality", "Scientific quality", "Design & Technical quality", "Technical soundness"],
     "desc": "Are methods appropriate and claims supported?"},
    {"key": "Impact", "synonyms": ["Significance", "Relevance", "Scientific impact"],
     "desc": "Will this advance the field or enable new capabilities?"},
    {"key": "Presentation", "synonyms": ["Clarity", "Quality of presentation"],
     "desc": "Is the paper well-written, organized, and easy to follow?"},
    {"key": "Positioning w.r.t Related Work", "synonyms": ["Meaningful Comparison"],
     "desc": "Is prior work covered fairly, with proper comparison?"},
    {"key": "Empirical Evaluation & Rigor", "synonyms": ["Ablations & Analyses", "Limitations / Threats to Validity", "Compute & Efficiency Reporting"],
     "desc": "Datasets, metrics, baselines; robustness (seeds, CIs, stress tests). Which components matter? Sensitivity & generalization checks. Hardware, train time, compute budget."},
    {"key": "Reproducibility", "synonyms": ["Technical Soundness", "Reusability", "Artifacts (Code/Data/Models Availability)"],
     "desc": "Sufficient detail to reproduce (hyperparams, data prep, runs). Code/data availability."},
    # {"key": "Relevance", "synonyms": ["Venue Fit / Relevance", "Relevance to the Conference"],
    #  "desc": "Match the call’s scope and audience."},
    {"key": "Strengths", "synonyms": [], "desc": "What are the main positive aspects of the paper?"},
    {"key": "Weaknesses", "synonyms": [], "desc": "What are the key shortcomings or concerns?"},
    {"key": "Limitations", "synonyms": [], "desc": "What are the limits of the work (scope, methods, applicability)?"},
    {"key": "Adequacy of citations", "synonyms": [], "desc": "Are references sufficient, accurate, and balanced?"},
    {"key": "Detailed comments to authors", "synonyms": [], "desc": "Constructive feedback to help the authors improve the work."},
]

